name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        java: ["8", "11"]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"
      - name: Prepare build tools
        run: git clone https://github.com/apache/dubbo/tree/master/dubbo-build-tools && ./mvnw clean install -pl dubbo-build-tools
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: ./mvnw -s .mvn/wrapper/settings.xml --batch-mode --no-transfer-progress clean install -DskipTests=false -DskipIntegrationTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true
