name: Extensions Conformance Tests

on:
  pull_request:
    paths:
      - "**"
      - "!**/*.md"
      - "!docs/**"
  push:
    paths:
      - '**'
      - "!**/*.md"
      - "!docs/**"

env:
  FORK_COUNT: 2
  FAIL_FAST: 0
  SHOW_ERROR_DETAIL: 1
  BUILD_OPTS: --batch-mode --no-snapshot-updates --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3 clean package dependency:copy-dependencies -DskipTests

jobs:
  build-extensions:
    name: "Build Extensions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dubbo-spi-extensions
      - uses: actions/checkout@v4
        with:
          repository: 'apache/dubbo'
          ref: '3.0'
          path: dubbo
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/cache@v4
        name: "Cache local Maven repository"
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-extensions-maven${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-extensions-maven
      - name: "Build tools"
        run: |
          cd ./dubbo
          ./mvnw --batch-mode -U -e --no-transfer-progress install -pl dubbo-build-tools -am -DskipTests=true
      - name: "Build with Maven"
        run: |
          cd ./dubbo-spi-extensions
          ./mvnw --batch-mode -U -e --no-transfer-progress install -am -DskipTests=true


  testjob:
    needs: [ prepare_test,build-extensions ]
    name: 'Conformance Test'
    runs-on: ubuntu-latest
    env:
      JAVA_VER: ${{matrix.java}}
    strategy:
      fail-fast: false
      matrix:
        # use the unsafe only run on the jdk8
        java: [ 8 ]
        #testjob id list MUST match 'JOB_COUNT' of 'prepare_test'
        job_id: [ 1,2,3 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{matrix.java}}
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-extensions-maven${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-extensions-maven
      - name: Download test list
        uses: actions/download-artifact@v4
        with:
          name: test-list
          path: test/jobs/
      - name: Build test image
        run: |
          cd test && bash ./build-test-image.sh
      - name: Run tests
        run: cd test && bash ./run-tests.sh
      - name: Upload log if test failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-log-${{matrix.java}}-${{matrix.job_id}}
          path: "**/test/scenarios/**/logs/*"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{matrix.job_id}}
          path: test/jobs/*-result*

  merge_test:
    needs: [ testjob ]
    name: 'Merge Test Result (Java${{matrix.java}})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
    env:
      JAVA_VER: ${{matrix.java}}
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: Merge-test-result-Java${{matrix.java}}
          separate-directories: true
          pattern: test-result-*
          delete-merged: true

#  test_result:
#    needs: [ testjob ]
#    name: 'Test Result (Java${{matrix.java}})'
#    if: always()
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        java: [ 8 ]
#    env:
#      JAVA_VER: ${{matrix.java}}
#    steps:
#      - uses: actions/checkout@v4
#      - name: Download test result
#        uses: actions/download-artifact@v4
#        with:
#          path: test/jobs/
#      - name: Merge test result - java ${{matrix.java}}
#        run: ./test/scripts/merge-test-results.sh
#      - name: Upload merge test result
#        uses: actions/upload-artifact@v4
#        with:
#          name: merge-test-result-${{matrix.java}}
#          path: test/jobs/*-result*
