name: Extensions Conformance Tests

on:
  pull_request:
    paths:
      - "**"
      - "!**/*.md"
      - "!docs/**"
  push:
    paths:
      - '**'
      - "!**/*.md"
      - "!docs/**"

env:
  FORK_COUNT: 2
  FAIL_FAST: 0
  SHOW_ERROR_DETAIL: 1
  BUILD_OPTS: --batch-mode --no-snapshot-updates --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3 clean package dependency:copy-dependencies -DskipTests

jobs:
  build-extensions:
    name: "Build Extensions"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dubbo-version:
          - "3.3"

    steps:
      - name: Checkout Dubbo SPI Extensions
        uses: actions/checkout@v4
        with:
          path: dubbo-spi-extensions

      - name: Checkout Apache Dubbo
        uses: actions/checkout@v4
        with:
          repository: apache/dubbo
          ref: ${{ matrix.dubbo-version }}
          path: dubbo
          fetch-depth: 0


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache local Maven repository
        uses: actions/cache@v4
        id: maven-cache
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.java }}-
            maven-${{ runner.os }}-
      

      - name: "Build with Maven"
        run: |
          cd ./dubbo-spi-extensions
          ./mvnw --batch-mode -U -e --no-transfer-progress install -am
  
  

  testjob:
    needs: [ build-extensions ]
    name: 'Conformance Test'
    runs-on: ubuntu-latest
    env:
      JAVA_VER: ${{matrix.java}}
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
        job_id: [ 1,2,3 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{matrix.java}}

      - name: "Cache local Maven repository"
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.java }}-
            maven-${{ runner.os }}-
      

  #    - name: Download test list
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: test-list
  #        path: test/jobs/
      - name: Build Test Image (if test folder exists)
        if: ${{ hashFiles('test/build-test-image.sh') != '' }}
        run: cd test && bash ./build-test-image.sh
      - name: Run tests
        run: |
          for i in {1..2}; do
            cd test && bash ./run-tests.sh && break || sleep 10;
          done
      - name: Upload log if test failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-log-${{matrix.java}}-${{matrix.job_id}}
          path: "**/test/scenarios/**/logs/*"
  #    - name: Upload test result
  #      if: always()
  #      uses: actions/upload-artifact@v4
  #      with:
  #        name: test-result-${{matrix.job_id}}
  #        path: test/jobs/*-result*

#  merge_test:
#    needs: [ testjob ]
#    name: 'Merge Test Result (Java${{matrix.java}})'
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        java: [ 17 ]
#    env:
#      JAVA_VER: ${{matrix.java}}
#    steps:
#      - name: Merge Artifacts
#        uses: actions/upload-artifact/merge@v4
#        with:
#          name: Merge-test-result-Java${{matrix.java}}
#          separate-directories: true
#          pattern: test-result-*
#          delete-merged: true

  test_result:
    needs: [ testjob ]
    name: 'Test Result (Java${{matrix.java}})'
    if: always()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    env:
      JAVA_VER: ${{matrix.java}}
    steps:
      - uses: actions/checkout@v4
      - name: Download test result
        uses: actions/download-artifact@v4
        with:
          path: test/jobs/
      - name: Upload merge test result
        uses: actions/upload-artifact@v4
        with:
          name: merge-test-result-${{matrix.java}}
          path: test/jobs/*-result*
